---
- name: Bootstrap new macbook
  hosts: localhost
  connection: local
  vars:
    fonts_details:
      - name: FiraCode
        archive:
          https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip
        directory: ttf
        files:
          - FiraCode-Bold.ttf
          - FiraCode-Light.ttf
          - FiraCode-Medium.ttf
          - FiraCode-Regular.ttf
          - FiraCode-Retina.ttf
  tasks:
    - name: Install casks
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: present
      loop:
        - iterm2
        - visual-studio-code
        - rectangle
        - bitwarden
        - vivaldi
        - docker
        - utm
        - firefox
      tags:
        - brew
        - casks
    - name: Install formulae
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - wget
        - pre-commit
        - ansible-lint
        - shellcheck
        - bitwarden-cli
        - jq
        - yq
        - golang
        - nvim
        - awscli
        - oh-my-posh
        - tflint
        - ack
        # Go Language Server
        - gopls
        - checkov
        - terraform
        - kubectx
        - eksctl
      tags:
        - brew
        - formulae
    - name: Update and upgrade homebrew software
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
    - name: Mac Fonts | Download repositories
      ansible.builtin.get_url:
        url: "{{ item.archive }}"
        dest: "/tmp/{{ item.archive.split('/') | last }}"
        mode: ug=rw
      with_items: "{{ fonts_details }}"
      tags:
        - fonts
        - never
    - name: Mac Fonts | Unzip
      ansible.builtin.unarchive:
        src: "/tmp/{{ item.archive.split('/') | last }}"
        dest: "/tmp"
      with_items: "{{ fonts_details }}"
      tags:
        - fonts
        - never
    - name: Mac Fonts | Install fonts from repositories
      ansible.builtin.copy:
        src: "/tmp/{{ item.0.directory }}/{{ item.1 }}"
        dest: "/Users/{{ lookup('env', 'USER') }}/Library/Fonts/{{ item.1 }}"
      with_subelements:
        - "{{ fonts_details }}"
        - "files"
      tags:
        - fonts
        - never
    - name: Add oh-my-posh to zshrc
      ansible.builtin.lineinfile:
        path: "/Users/{{ lookup('env', 'USER') }}/.zshrc"
        line: eval "$(oh-my-posh init zsh)"
        state: present
        search_string: "oh-my-posh init zsh"
      tags:
        - config_files
    - name: Pimp my nvim courtesy of James Tooze | clone
      ansible.builtin.git:
        dest: "/tmp/neovimfiles"
        repo: "https://github.com/toozej/neovimfiles.git"
        single_branch: true
      tags:
        - config_files
        - neovim
    - name: Pimp my nvim courtesy of James Tooze | install
      ansible.builtin.command:
        cmd: ./setup.sh
        chdir: /tmp/neovimfiles
      tags:
        - config_files
        - neovim
